// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// qatd_cpp_tokens_kwic
List qatd_cpp_tokens_kwic(const List& texts_, const CharacterVector& types_, const List& words_, const unsigned int& window);
RcppExport SEXP _quanteda_features_qatd_cpp_tokens_kwic(SEXP texts_SEXP, SEXP types_SEXP, SEXP words_SEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type texts_(texts_SEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type types_(types_SEXP);
    Rcpp::traits::input_parameter< const List& >::type words_(words_SEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(qatd_cpp_tokens_kwic(texts_, types_, words_, window));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_quanteda_features_qatd_cpp_tokens_kwic", (DL_FUNC) &_quanteda_features_qatd_cpp_tokens_kwic, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_quanteda_features(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
