# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qatd_cpp_tokens_kwic <- function(texts_, types_, words_, window) {
    .Call('_quanteda_features_qatd_cpp_tokens_kwic', PACKAGE = 'quanteda.features', texts_, types_, words_, window)
}

